require: 'rubocop-rspec'

AllCops:
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'
  NewCops: enable

Layout/ExtraSpacing:
  Exclude:
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Style/Documentation:
  Enabled: false
