require: 'rubocop-rspec'

AllCops:
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 6

Style/Documentation:
  Enabled: false
