require: 'rubocop-rspec'

AllCops:
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe

Style/Documentation:
  Enabled: false
