require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - vendor/**/*
  NewCops: enable

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe

Rails/CreateTableWithTimestamps:
  Enabled: false

Style/Documentation:
  Enabled: false
