AllCops:
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
