language: ruby
cache: bundler
env:
  global:
    - RACK_ENV=test
install:
  - bundle config set --local deployment 'true'
  - bundle config set --local with 'test'
  - bundle config set --local without 'development:production'
  - bundle install --jobs=3 --retry=3
before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
branches:
  only:
  - main
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
