language: ruby
cache: bundler
env:
  global:
    - RACK_ENV=test
sudo: required
before_install:
  - sudo ./spec/bin/install-freetds.sh
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
