# Because our application never writes to the database, you *can* tunnel
# through the production server to the prod database if you have to
# ssh -v -N -L 14333:sqlserver:1433 user@prodwebserver
development:
  adapter:  sqlserver
  host:     127.0.0.1
  database: <%= EAMApp.credentials.dig(:database, :database) %>
  username: <%= EAMApp.credentials.dig(:database, :username) %>
  password: <%= EAMApp.credentials.dig(:database, :password) %>
  port:     14333

test:
  adapter: sqlite3
  database: db/test.db
  pool: 5
  timeout: 5000
