#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../config/environment'
require 'eam_app'

$stdout.sync = true
IRB.setup nil
IRB.conf.tap do |c|
  prompt = c[:PROMPT][:DEFAULT].dup
  prompt[:RETURN] = "##{prompt[:RETURN]}"

  c[:IRB_NAME] = 'fleetfocus-api'
  c[:PROMPT][:CUSTOM] = prompt
  c[:PROMPT_MODE] = :CUSTOM
end

IRB::Irb.new.run(IRB.conf)
