source :gemcutter

gem 'haml'
gem 'sinatra'
gem 'thin'
gem 'activerecord-sqlserver-adapter', "~>2.0" #https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/2-3-stable_deadlock
gem 'tiny_tds'

group :development, :test do
  gem 'rspec', "=1.3.2"
  gem 'rack-test'
  gem 'test-unit', "=1.2.3"
  gem 'factory_girl'
  gem 'rr'
end
