name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install freetds
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: bin/rubocop
  rspec:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install freetds
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - run: script/setup
      - run: bin/rspec
