name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag fleetfocus-api --build-arg RUBY_VERSION="$(cat .ruby-version)" .
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bin/rubocop
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          database: true
      - run: bin/rspec
