name: pull_request
permissions:
  contents: read
on:
  pull_request:
jobs:
  integrate-docker:
    name: integrate
    uses: umts/.github/.github/workflows/integrate-docker.yml@c3317262d7da3ba37190f8d182a23cd106cf8e8f
  integrate-rspec:
    name: integrate
    uses: umts/.github/.github/workflows/integrate-rspec.yml@c3317262d7da3ba37190f8d182a23cd106cf8e8f
    with:
      setup_command: bin/rake db:prepare
  integrate-rubocop:
    name: integrate
    uses: umts/.github/.github/workflows/integrate-rubocop.yml@c3317262d7da3ba37190f8d182a23cd106cf8e8f
