name: push
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  integrate:
    uses: ./.github/workflows/integrate.yml
  deploy:
    needs: integrate
    permissions:
      pages: write
      id-token: write
    uses: umts/shared-workflows/.github/workflows/ghcr-kamal.yml@d82f3a191645340d5504873d32ca683ebf3c040a
